import { createArtist } from '@/db/artists'
import { createEvent } from '@/db/events'

interface ArtistSeed {
  name: string
  color: string
}

interface EventSeed {
  artistNames: string[]
  title: string
  date: string
  startTime?: string
  venue?: string
  url?: string
  note?: string
}

// Artist 代表色：柔和亮色 (Tailwind 300 系列，低飽和度高明度)
const ARTISTS: ArtistSeed[] = [
  { name: 'TrySail', color: '#93C5FD' },
  { name: '私立恵比寿中学', color: '#67E8F9' },
  { name: '高嶺のなでしこ', color: '#FDBA74' },
  { name: '僕が見たかった青空', color: '#5EEAD4' },
  { name: '超ときめき♡宣伝部', color: '#E879F9' },
  { name: 'SWEET STEADY', color: '#86EFAC' },
  { name: 'CUTIE STREET', color: '#FB7185' },
  { name: 'Juice=Juice', color: '#FDE047' },
  { name: 'ももいろクローバーZ', color: '#FCA5A5' },
]

const CUTIE_ARENA_TOUR = 'CUTIE STREET JAPAN ARENA TOUR 2026 -AUTUMN-'

const EBICHU_TOUR = '私立恵比寿中学 Spring Tour 2026 〜SuGuilty Train〜'
const TOKISEN_TOUR = '超ときめき♡宣伝部のきみのハートにロックオンTOUR 2026'
const JJ_5ROOMS = 'Juice=Juice Room Tour 2026 「5ROOMS」'
const JJ_5ROOMS_URL =
  'https://helloproject.com/event/ac7ec0bd437f3af1f9fcdc9c579f31312e9112fe13471d9fbae91c755990d6f2/'
const TRYSAIL_TRICK = 'LAWSON presents TrySail Event 2026「コワイセイルのTrick運動会」'
const MOMO_RELIER = 'LAWSON presents 麻倉もも 10th Anniversary Live Tour 2027 “relier”'
const MOMO_RELIER_URL = 'https://trysail.jp/contents/1107228'
const SHIINA_MONA = 'LAWSON presents 夏川椎菜 as mona 3rdワンマンライブ motto☆motto愛を歌おうぜ♡'
const SHIINA_MONA_URL = 'https://trysail.jp/contents/1089115'
const MOMOCLO_XMAS = 'ももいろクローバーZ クリスマスツアー2026「ももクリDelivery」'
const MOMOCLO_XMAS_URL = 'https://www.momoclo.net/archives/news/260727_03'
const SWESTE_TOUR = 'SWEET STEADY JAPAN TOUR 2026 -WINTER-'
const SWESTE_RELEASE = '3rdシングル『SWEET STEP』発売記念リリースイベント'
const SOUND_OF_EBICHU = 'SOUND OF EBICHU 2026 -Band Edition-'
const BOKUAO_9TH = '僕が見たかった青空 9thシングル発売記念'

// 2026 年 2 月〜2027 年 3 月主要 live / tour（依公開資料，日期 JST）
const EVENTS: EventSeed[] = [
  // ── 高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – (Feb–May) ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Sapporo',
    date: '2026-02-14',
    venue: 'Zepp Sapporo (北海道)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Osaka',
    date: '2026-02-23',
    venue: 'Zepp Osaka Bayside (大阪)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Nagoya',
    date: '2026-03-01',
    venue: 'Zepp Nagoya (愛知)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Tokyo',
    date: '2026-03-07',
    venue: 'Zepp DiverCity TOKYO',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Fukuoka',
    date: '2026-03-21',
    venue: 'Zepp Fukuoka (福岡)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Sendai',
    date: '2026-03-29',
    venue: '仙台PIT (宮城)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Seoul',
    date: '2026-04-12',
    venue: 'Seoul (Korea)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Taipei 昼公演',
    date: '2026-04-18',
    startTime: '13:00',
    venue: 'MOONDOG (台北市松山區復興南路一段39号9F)',
    url: 'https://takanenonadeshiko.jp/bouquetof9flowers-taipei/',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – in Taipei 夜公演',
    date: '2026-04-18',
    startTime: '19:00',
    venue: 'MOONDOG (台北市松山區復興南路一段39号9F)',
    url: 'https://takanenonadeshiko.jp/bouquetof9flowers-taipei/',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ Live Tour – Bouquet of 9 Flowers – FINAL',
    date: '2026-05-06',
    venue: '東京国際フォーラム ホールA (東京)',
  },

  // ── TrySail 10th Anniversary Live "Cheers!!!" (May) ──
  {
    artistNames: ['TrySail'],
    title: 'TrySail 10th Anniversary Live 2026 "Cheers!!!"',
    date: '2026-05-10',
    venue: 'グランキューブ大阪 メインホール (大阪)',
    url: 'https://trysail.jp/contents/989829',
  },
  {
    artistNames: ['TrySail'],
    title: 'TrySail 10th Anniversary Live 2026 "Cheers!!!"',
    date: '2026-05-17',
    venue: 'パシフィコ横浜 国立大ホール (神奈川)',
    url: 'https://trysail.jp/contents/989829',
  },

  // ── TrySail 系列：團體及成員個人活動共用分類 ──
  // 2026-09-06 核對；同日不同場次分開收錄，時間為開演時間。
  {
    artistNames: ['TrySail'],
    title: 'TrySail Blu-ray 発売記念プレミア上映会 ①回',
    date: '2026-10-04',
    startTime: '11:30',
    venue: 'ユナイテッド・シネマ豊洲 (東京)',
    url: 'https://trysail.jp/contents/1100924',
    note: '上映後に舞台挨拶。¥3,500、3人登壇',
  },
  {
    artistNames: ['TrySail'],
    title: 'TrySail Blu-ray 発売記念プレミア上映会 ②回',
    date: '2026-10-04',
    startTime: '15:00',
    venue: 'ユナイテッド・シネマ豊洲 (東京)',
    url: 'https://trysail.jp/contents/1100924',
    note: '上映前に舞台挨拶。¥3,500、3人登壇',
  },
  {
    artistNames: ['TrySail'],
    title: '夏川椎菜 リーディングシアター「シャーロック・ホームズ」',
    date: '2026-10-23',
    startTime: '19:00',
    venue: '銀座 博品館劇場 (東京)',
    note: '夏川椎菜のみ出演',
  },

  // ── 夏川椎菜 as mona：神戸1場、東京昼夜2場 ──
  {
    artistNames: ['TrySail'],
    title: `${SHIINA_MONA} — 神戸`,
    date: '2026-12-06',
    startTime: '18:00',
    venue: '神戸国際会館 こくさいホール (兵庫)',
    url: SHIINA_MONA_URL,
    note: '夏川椎菜個人公演（mona役）。開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${SHIINA_MONA} — 東京 昼公演`,
    date: '2026-12-13',
    startTime: '15:00',
    venue: 'Shibuya LOVEZ (東京)',
    url: SHIINA_MONA_URL,
    note: '夏川椎菜個人公演（mona役）。開場 14:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${SHIINA_MONA} — 東京 夜公演`,
    date: '2026-12-13',
    startTime: '18:30',
    venue: 'Shibuya LOVEZ (東京)',
    url: SHIINA_MONA_URL,
    note: '夏川椎菜個人公演（mona役）。開場 17:30',
  },

  // ── 麻倉もも relier：2026-09-05 公布，5都市7公演 ──
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 愛知`,
    date: '2027-01-09',
    startTime: '18:00',
    venue: 'Niterra日本特殊陶業市民会館 フォレストホール (愛知)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 大阪 DAY1`,
    date: '2027-01-16',
    startTime: '18:00',
    venue: 'NHK大阪ホール (大阪)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 大阪 DAY2`,
    date: '2027-01-17',
    startTime: '17:00',
    venue: 'NHK大阪ホール (大阪)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 16:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 福岡`,
    date: '2027-01-30',
    startTime: '17:00',
    venue: '福岡国際会議場 メインホール (福岡)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 16:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 宮城`,
    date: '2027-02-07',
    startTime: '18:00',
    venue: '電力ホール (宮城)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 東京 DAY1`,
    date: '2027-02-20',
    startTime: '18:00',
    venue: 'Shibuya LOVEZ (東京)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${MOMO_RELIER} — 東京 DAY2`,
    date: '2027-02-21',
    startTime: '17:00',
    venue: 'Shibuya LOVEZ (東京)',
    url: MOMO_RELIER_URL,
    note: '麻倉もも個人巡迴。開場 16:00',
  },

  // ── TrySail コワイセイルのTrick運動会（運動会×ハロウィン企画イベント） ──
  {
    artistNames: ['TrySail'],
    title: `${TRYSAIL_TRICK} — 神戸`,
    date: '2026-10-18',
    startTime: '18:00',
    venue: '神戸国際会館 こくさいホール (兵庫)',
    url: 'https://trysail.jp/contents/1101837',
    note: '開場 17:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${TRYSAIL_TRICK} — 東京 DAY1 昼公演`,
    date: '2026-10-31',
    startTime: '15:30',
    venue: 'Shibuya LOVEZ (東京)',
    url: 'https://trysail.jp/contents/1101837',
    note: '開場 14:30',
  },
  {
    artistNames: ['TrySail'],
    title: `${TRYSAIL_TRICK} — 東京 DAY1 夜公演`,
    date: '2026-10-31',
    startTime: '19:00',
    venue: 'Shibuya LOVEZ (東京)',
    url: 'https://trysail.jp/contents/1101837',
    note: '開場 18:00',
  },
  {
    artistNames: ['TrySail'],
    title: `${TRYSAIL_TRICK} — 東京 DAY2 昼公演`,
    date: '2026-11-01',
    startTime: '13:30',
    venue: 'Shibuya LOVEZ (東京)',
    url: 'https://trysail.jp/contents/1101837',
    note: '開場 12:30',
  },
  {
    artistNames: ['TrySail'],
    title: `${TRYSAIL_TRICK} — 東京 DAY2 夜公演`,
    date: '2026-11-01',
    startTime: '17:00',
    venue: 'Shibuya LOVEZ (東京)',
    url: 'https://trysail.jp/contents/1101837',
    note: '開場 16:00',
  },

  // ── エビ中 Spring Tour 2026 〜SuGuilty Train〜 (Apr–Jul, 12 公演) ──
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-04-18',
    venue: 'ザ・ヒロサワ・シティ会館 大ホール (茨城)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-04-25',
    venue: '刈谷市総合文化センター 大ホール (愛知)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-04-29',
    venue: '福岡国際会議場 メインホール (福岡)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-05-10',
    venue: '東京エレクトロンホール宮城 (宮城)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-05-17',
    venue: '大宮ソニックシティ 大ホール (埼玉)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-05-23',
    venue: '新潟県民会館 大ホール (新潟)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-06-06',
    venue: 'Kanadevia Hall (東京)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-06-07',
    venue: 'Kanadevia Hall (東京)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-07-04',
    venue: 'NHK 大阪ホール (大阪)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: EBICHU_TOUR,
    date: '2026-07-05',
    venue: 'NHK 大阪ホール (大阪)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: `${EBICHU_TOUR} 追加公演`,
    date: '2026-07-11',
    venue: '立川ステージガーデン (東京)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: `${EBICHU_TOUR} 追加公演`,
    date: '2026-07-12',
    venue: '立川ステージガーデン (東京)',
  },

  // ── エビ中 × ukka ツーマンライブ（ukka は 2026 年 5 月解散） ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '私立恵比寿中学 × ukka ツーマンライブ',
    date: '2026-05-12',
    venue: 'Zepp Haneda (TOKYO)',
  },

  // ── エビ中 メンバー個人生誕ソロライブ ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '仲村悠菜 生誕ソロライブ「純喫茶ミルクティー〜4杯目〜」',
    date: '2026-05-28',
    startTime: '19:00',
    venue: 'KT Zepp Yokohama (神奈川)',
    note: 'エビ中 仲村悠菜 個人生誕祭、4 回目',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '風見和香 生誕ソロライブ',
    date: '2026-08-31',
    startTime: '19:00',
    venue: 'KT Zepp Yokohama (神奈川)',
    url: 'https://www.shiritsuebichu.jp/media/15616/',
    note: 'エビ中 風見和香 個人生誕祭。開場 18:15、1公演のみ',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '桜井えま 生誕ソロライブ「はにーえまいる〜沼4〜」',
    date: '2026-09-08',
    startTime: '19:00',
    venue: 'Zepp DiverCity (TOKYO)',
    url: 'https://www.shiritsuebichu.jp/media/15617/',
    note: 'エビ中 桜井えま 個人生誕祭。開場 18:15、1公演のみ、指定席 ¥6,900',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '桜木心菜 生誕ソロライブ「桜木Night Prom〜midnight fever〜」',
    date: '2026-09-15',
    startTime: '19:00',
    venue: 'Zepp DiverCity (TOKYO)',
    url: 'https://www.shiritsuebichu.jp/media/15618/',
    note: 'エビ中 桜木心菜 個人生誕祭。開場 18:15、1公演のみ、終演後お見送り会あり',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '中山莉子 生誕ソロライブ',
    date: '2026-10-26',
    venue: 'Zepp DiverCity (TOKYO)',
    url: 'https://www.shiritsuebichu.jp/media/15619/',
    note: 'エビ中 中山莉子 個人生誕祭。時間未発表',
  },

  // ── エビ中 真山りか 主演 リーディング・オペラ Op.4「トスカ」（1日2公演 × 2日） ──
  {
    artistNames: ['私立恵比寿中学'],
    title: 'リーディング・オペラ Op.4「トスカ」DAY1 昼公演',
    date: '2026-09-09',
    startTime: '15:00',
    venue: 'ルーテル市ヶ谷ホール (東京)',
    url: 'https://www.shiritsuebichu.jp/media/15972/',
    note: 'エビ中 真山りか 主演（岸本勇太 / 石井雅登 / 今拓哉 出演）',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'リーディング・オペラ Op.4「トスカ」DAY1 夜公演',
    date: '2026-09-09',
    startTime: '19:00',
    venue: 'ルーテル市ヶ谷ホール (東京)',
    url: 'https://www.shiritsuebichu.jp/media/15972/',
    note: 'エビ中 真山りか 主演（岸本勇太 / 石井雅登 / 今拓哉 出演）',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'リーディング・オペラ Op.4「トスカ」DAY2 昼公演',
    date: '2026-09-10',
    startTime: '15:00',
    venue: 'ルーテル市ヶ谷ホール (東京)',
    url: 'https://www.shiritsuebichu.jp/media/15973/',
    note: 'エビ中 真山りか 主演（岸本勇太 / 石井雅登 / 今拓哉 出演）',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'リーディング・オペラ Op.4「トスカ」DAY2 夜公演',
    date: '2026-09-10',
    startTime: '19:00',
    venue: 'ルーテル市ヶ谷ホール (東京)',
    url: 'https://www.shiritsuebichu.jp/media/15973/',
    note: 'エビ中 真山りか 主演（岸本勇太 / 石井雅登 / 今拓哉 出演）',
  },

  // ── エビ中 FAMIEN 2026（8/8–9 @ 山中湖） ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '夏のファミリー遠足 略してファミえん 2026',
    date: '2026-08-08',
    venue: '山中湖交流プラザきららシアターひびき (山梨)',
    note: 'FAMIEN 2026',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '夏のファミリー遠足 略してファミえん 2026',
    date: '2026-08-09',
    venue: '山中湖交流プラザきららシアターひびき (山梨)',
    note: 'FAMIEN 2026',
  },

  // ── LuckyFes'26 (@ 国営ひたち海浜公園, 茨城) ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'LuckyFes\'26 DAY2',
    date: '2026-08-09',
    startTime: '13:20',
    venue: '国営ひたち海浜公園 GARDEN STAGE (茨城)',
    url: 'https://luckyfes.com/',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'LuckyFes\'26 DAY3',
    date: '2026-08-10',
    venue: '国営ひたち海浜公園 (茨城)',
    url: 'https://luckyfes.com/',
  },

  // ── TIF 2026 (7/31–8/2 @ お台場・青海) ──
  {
    artistNames: [
      '私立恵比寿中学',
      '高嶺のなでしこ',
      'SWEET STEADY',
      'CUTIE STREET',
      '超ときめき♡宣伝部',
    ],
    title: 'TOKYO IDOL FESTIVAL 2026 DAY1',
    date: '2026-07-31',
    venue: 'お台場・青海エリア (東京)',
    url: 'https://official.idolfes.com/s/tif2026/',
  },
  {
    artistNames: ['高嶺のなでしこ', '僕が見たかった青空'],
    title: 'TOKYO IDOL FESTIVAL 2026 DAY2',
    date: '2026-08-01',
    venue: 'お台場・青海エリア (東京)',
    url: 'https://official.idolfes.com/s/tif2026/',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'TOKYO IDOL FESTIVAL 2026 DAY3',
    date: '2026-08-02',
    venue: 'お台場・青海エリア (東京)',
    url: 'https://official.idolfes.com/s/tif2026/',
  },

  // ── エビ中 夏フェス出演 ──
  {
    artistNames: ['私立恵比寿中学'],
    title: 'Heavy Kawaii Fes 2026 Day2 -私立恵比寿中学 × KOIAI-',
    date: '2026-08-01',
    startTime: '13:00',
    venue: '明治座 (東京)',
    url: 'https://www.shiritsuebichu.jp/news/15982/',
    note: 'DAY 13:00 / NIGHT 18:00 の2公演、稲場愛香 / KOIAI と共演',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'めざましWANGANフェス めざましライブ',
    date: '2026-08-04',
    venue: '豊洲PIT (東京)',
    note: 'イマドキ対バン、ねぎ塩豚丼と共演',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'テレビ朝日・六本木ヒルズ SUMMER FES 音楽LIVE',
    date: '2026-08-14',
    venue: '六本木ヒルズ (東京)',
  },

  // ── エビ中 SOUND OF EBICHU 2026（新ライブシリーズ、バンド編成。ちゅうおんの後継） ──
  {
    artistNames: ['私立恵比寿中学'],
    title: `${SOUND_OF_EBICHU} — 横浜`,
    date: '2026-10-11',
    startTime: '18:00',
    venue: 'パシフィコ横浜 国立大ホール (神奈川)',
    url: 'https://www.shiritsuebichu.jp/news/16044/',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: `${SOUND_OF_EBICHU} — 神戸`,
    date: '2026-11-08',
    startTime: '18:00',
    venue: '神戸国際会館 こくさいホール (兵庫)',
    url: 'https://www.shiritsuebichu.jp/news/16044/',
  },

  // ── エビ中 桜井えま 1st写真集「あざと未満」(9/4 発売) イベント ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '桜井えま 1st写真集「あざと未満」発売記念イベント in 東京',
    date: '2026-09-05',
    startTime: '16:00',
    venue: 'HMV&BOOKS SHIBUYA 5F イベントスペース (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95110/',
    note: '2部制 16:00 / 18:30、部ごとに衣装チェンジ',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '桜井えま 1st写真集「あざと未満」発売記念イベント in 大阪',
    date: '2026-09-20',
    startTime: '13:00',
    venue: '紀伊國屋書店グランフロント大阪店 (大阪)',
    url: 'https://www.shiritsuebichu.jp/media/95111/',
    note: '2部制 13:00 / 15:00',
  },

  // ── エビ中 その他 2026 秋 ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '新宿警察署 一日警察署長',
    date: '2026-09-06',
    startTime: '10:40',
    venue: '新宿通り・新宿駅東口トラックステージ (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95862/',
    note: '無料・屋外。パレード 10:40 頃〜、交通安全宣言 11:00 頃〜',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '私立恵比寿中学×namco TOKYO コラボカフェ〜えびチリ、はじめました〜',
    date: '2026-09-14',
    venue: '東急歌舞伎町タワー3F namco TOKYO (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95847/',
    note: '会期 9/14〜9/27、事前抽選制（無料）',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'namco TOKYO コラボカフェ プレミアムイベント トークショー',
    date: '2026-09-21',
    startTime: '13:00',
    venue: '東急歌舞伎町タワー3F namco TOKYO (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95847/',
    note: '¥5,000、事前抽選',
  },
  {
    artistNames: ['私立恵比寿中学', '僕が見たかった青空'],
    title: 'TBS「SASUKEアイドル予選会2026 -出場権争奪バトル-」',
    date: '2026-10-01',
    startTime: '18:30',
    venue: 'キッコーマンアリーナ 流山市民総合体育館 (千葉)',
    url: 'https://www.shiritsuebichu.jp/news/16107/',
    note: 'エビ中 風見和香 / 僕青 須永心海 出場。開場 17:30、一般先着 9/5 10:00〜',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'TORIDE GP 2026 Fujishiro Demo Run',
    date: '2026-10-03',
    venue: '取手・藤代 (茨城)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'Spicy Sessions -THE LIVE- 2026',
    date: '2026-10-20',
    venue: '会場未発表',
    note: '真山りか・安本彩花のみ出演',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'ZOMBIE FES 2026 DAY1',
    date: '2026-10-29',
    venue: '横須賀うみかぜ公園 (神奈川)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'ちかっぱ祭2026',
    date: '2026-11-23',
    venue: 'マリンメッセ福岡B館 (福岡)',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '夏のファミリー遠足 略してファミえん 2027 DAY1',
    date: '2027-08-07',
    venue: '山中湖交流プラザきららシアターひびき (山梨)',
    url: 'https://www.shiritsuebichu.jp/news/16137/',
    note: 'FAMIEN 2027、詳細後日',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '夏のファミリー遠足 略してファミえん 2027 DAY2',
    date: '2027-08-08',
    venue: '山中湖交流プラザきららシアターひびき (山梨)',
    url: 'https://www.shiritsuebichu.jp/news/16137/',
    note: 'FAMIEN 2027、詳細後日',
  },

  // ── 僕が見たかった青空 2026 秋（9月はメンバー個人仕事のみ） ──
  {
    artistNames: ['僕が見たかった青空'],
    title: 'J1 ジェフ千葉 vs G大阪「浅井ヘルスケア グループ マッチデー」',
    date: '2026-09-06',
    startTime: '16:20',
    venue: 'フクダ電子アリーナ 北芝生広場（場外）(千葉)',
    url: 'https://bokuao.com/schedule/detail/5720',
    note: '青木宙帆のみ。トークステージ 16:20 頃〜',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '劇場型マーダーミステリー「生放送は、止まらない」',
    date: '2026-09-14',
    startTime: '13:00',
    venue: '座・高円寺2 (東京)',
    url: 'https://bokuao.com/schedule/detail/5672',
    note: '吉本此那のみ出演',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: 'クロフェス2026 7年目 ラッキー7アイドルフィーバーだしん！',
    date: '2026-10-02',
    venue: '稲毛海浜公園プール (千葉)',
    url: 'https://bokuao.com/news/detail/5754',
    note: 'フェスは 10/2-4 開催、僕青の出演日は公式未指定（要確認）',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '青春SPARK祭',
    date: '2026-10-11',
    venue: '静岡県内 (会場未発表)',
    url: 'https://bokuao.com/schedule/detail/5583',
    note: '僕青がアンバサダー就任',
  },

  // ── エビ中 舞台「けものフレンズ」×私立恵比寿中学（全8人出演） ──
  {
    artistNames: ['私立恵比寿中学'],
    title: '舞台「けものフレンズ」×私立恵比寿中学',
    date: '2026-12-04',
    startTime: '12:00',
    venue: '品川プリンスホテル ステラボール (東京)',
    url: 'https://kemono-friends-butai.jp/schedule.html',
    note: '初日、2公演 12:00 / 18:00',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '舞台「けものフレンズ」×私立恵比寿中学',
    date: '2026-12-05',
    startTime: '13:30',
    venue: '品川プリンスホテル ステラボール (東京)',
    url: 'https://kemono-friends-butai.jp/schedule.html',
    note: '2公演 13:30 / 16:30',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '舞台「けものフレンズ」×私立恵比寿中学',
    date: '2026-12-06',
    startTime: '12:00',
    venue: '品川プリンスホテル ステラボール (東京)',
    url: 'https://kemono-friends-butai.jp/schedule.html',
    note: '千穐楽、2公演 12:00 / 16:30',
  },

  // ── 高嶺のなでしこ 4周年記念 ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ 4周年 Special LIVE',
    date: '2026-08-06',
    venue: 'KT Zepp Yokohama (神奈川)',
    url: 'https://takanenonadeshiko.jp/takaneko-4thanniversarylive/',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ 4th ファンミーティング',
    date: '2026-08-07',
    venue: 'ヒューリックホール東京 (東京)',
    note: '詳細後日発表',
  },

  // ── 高嶺のなでしこ 2026 夏〜秋（★8/25 星谷美来 卒業公演） ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'ふぁぼフェス♡',
    date: '2026-08-22',
    startTime: '13:30',
    venue: 'Zepp Shinjuku (東京)',
    note: '対バンフェス出演',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'メ〜テレ MUSIC DAYS',
    date: '2026-08-23',
    venue: '東別院テラスホール (愛知)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '星谷美来 卒業公演〜ずっと恋の病でいてね〜',
    date: '2026-08-25',
    startTime: '18:30',
    venue: '恵比寿ガーデンホール (東京)',
    url: 'https://takanenonadeshiko.jp/hoshitanimikuru-0825/',
    note: '星谷美来 グループ卒業公演',
  },
  {
    artistNames: ['高嶺のなでしこ', '私立恵比寿中学'],
    title: '@JAM EXPO 2026 DAY1',
    date: '2026-08-29',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://atjam.jp/expo2026',
    note: '高城れに（ももクロ）ソロも同日出演',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '24時間テレビ 日産チャリティーイベント',
    date: '2026-08-30',
    venue: '日産本社グローバルギャラリー (神奈川)',
    note: '無料イベント',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'ジャムズセッション!!Vol.8',
    date: '2026-09-10',
    startTime: '16:30',
    venue: '品川ステラボール (東京)',
    note: '対バン、たかねこ出演枠 19:45〜20:10',
  },

  // ── 高嶺のなでしこ 2ndアルバム『A World in Our Colors』(11/18) リリイベ series ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』発売記念 オンラインサイン会',
    date: '2026-09-05',
    startTime: '13:00',
    venue: 'オンライン (SHOWROOM)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors-0905-1/',
    note: '1部 13:00 城月/橋本/東山/松本、2部 14:20 涼海/葉月/日向端/籾山。アーカイブなし',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』発売記念 オンラインお話し会',
    date: '2026-09-05',
    startTime: '15:40',
    venue: 'オンライン (リミスタ)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors-0905-2/',
    note: '1部 15:40 / 2部 17:00。たかねこ盤予約で 30 秒/枚',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念イベント 1部',
    date: '2026-09-06',
    startTime: '12:30',
    venue: '有明ガーデン モール棟3F みんなのテラス (東京)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors-0906/',
    note: 'ミニライブ観覧フリー、1部はグループショット撮影会。優先エリア入場 12:10 / CD販売 10:00〜',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念イベント 2部',
    date: '2026-09-06',
    startTime: '16:00',
    venue: '有明ガーデン モール棟3F みんなのテラス (東京)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors-0906/',
    note: 'ミニライブ観覧フリー、2部はグループ握手会。優先エリア入場 15:40',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念イベント（ミニライブ&特典会）',
    date: '2026-09-12',
    venue: '埼玉県内某所 (埼玉)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors/',
    note: '会場・時間とも未発表',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念イベント（ミニライブ&特典会）',
    date: '2026-09-19',
    venue: '千葉県内某所 (千葉)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors/',
    note: '会場・時間とも未発表',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念 個別握手会',
    date: '2026-09-21',
    venue: '都内某所 (東京)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors/',
    note: '会場・時間とも未発表',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念 グループ特典会',
    date: '2026-09-22',
    venue: '埼玉県内某所 (埼玉)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors/',
    note: '会場・時間とも未発表',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '『A World in Our Colors』リリース記念イベント（ミニライブ&特典会）',
    date: '2026-09-26',
    venue: '神奈川県内某所 (神奈川)',
    url: 'https://takanenonadeshiko.jp/newalbum-aworldinourcolors/',
    note: '会場・時間とも未発表',
  },

  // ── 高嶺のなでしこ 秋の対バン / フェス ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: '赤レンガスプラッシュ祭 -Day2-',
    date: '2026-09-09',
    startTime: '11:30',
    venue: '横浜赤レンガ倉庫イベント広場B (神奈川)',
    note: '21組出演の対バン',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'MARQUEE Fes.',
    date: '2026-09-16',
    startTime: '14:30',
    venue: 'Spotify O-EAST (東京)',
    note: '16組対バン',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '文化放送 presents「idoLove You♫ -On Stage QR- vol.2」',
    date: '2026-09-17',
    startTime: '10:00',
    venue: '品川ステラボール (東京)',
    note: '19組対バン',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'SPARK2026 in YAMANAKAKO',
    date: '2026-09-23',
    startTime: '10:00',
    venue: '山中湖交流プラザきらら (山梨)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '推し寺アイドルまつり2026',
    date: '2026-10-04',
    startTime: '15:00',
    venue: '東別院テラスホール (愛知)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'TOKYO GIRLS GIRLS',
    date: '2026-10-06',
    startTime: '11:20',
    venue: 'Shibuya LOVEZ (東京)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: '衛星とカラテア presents「超 明星現象 2026」',
    date: '2026-10-07',
    startTime: '15:00',
    venue: 'Shibuya LOVEZ (東京)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'HoneyWorks presents ハニフェス2026 〜女子校文化祭 ハロウィンパーティ〜',
    date: '2026-10-18',
    startTime: '17:30',
    venue: 'Shibuya LOVEZ (東京)',
    note: 'ハコニワリリィ / 可憐なアイボリー と共演',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'ZOMBIE FES 2026 DAY3 1部',
    date: '2026-10-31',
    startTime: '14:00',
    venue: '横須賀うみかぜ公園 特設ステージ (神奈川)',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'ZOMBIE FES 2026 DAY3 2部',
    date: '2026-10-31',
    startTime: '18:00',
    venue: '横須賀うみかぜ公園 特設ステージ (神奈川)',
  },

  // ── 僕が見たかった青空 全国ツアー2026 + 音楽祭 + 3周年野外 + サマフェス ──
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が見たかった青空 全国ツアー2026 — 大阪 1部',
    date: '2026-05-02',
    startTime: '14:30',
    venue: 'GORILLA HALL OSAKA (大阪)',
    url: 'https://bokuao.com/feature/2026spring',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が見たかった青空 全国ツアー2026 — 大阪 2部',
    date: '2026-05-02',
    startTime: '18:00',
    venue: 'GORILLA HALL OSAKA (大阪)',
    url: 'https://bokuao.com/feature/2026spring',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が見たかった青空 全国ツアー2026 — 名古屋 1部',
    date: '2026-05-09',
    startTime: '14:30',
    venue: 'DIAMOND HALL (愛知)',
    url: 'https://bokuao.com/feature/2026spring',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が見たかった青空 全国ツアー2026 — 名古屋 2部',
    date: '2026-05-09',
    startTime: '18:00',
    venue: 'DIAMOND HALL (愛知)',
    url: 'https://bokuao.com/feature/2026spring',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: 'EARLY SUMMER FESTA 2026 僕青音楽祭 — 1部',
    date: '2026-05-06',
    startTime: '13:45',
    venue: 'うみかぜ公園 特設野外ステージ (神奈川 横須賀)',
    url: 'https://esfes.jp/music/260506/',
    note: 'OCEANS BAND 生演奏 / 海際野外ステージ',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: 'EARLY SUMMER FESTA 2026 僕青音楽祭 — 2部',
    date: '2026-05-06',
    startTime: '17:45',
    venue: 'うみかぜ公園 特設野外ステージ (神奈川 横須賀)',
    url: 'https://esfes.jp/music/260506/',
    note: 'OCEANS BAND 生演奏 / 海際野外ステージ',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が観たかった『青空野外』ライブ2026',
    date: '2026-06-20',
    venue: '河口湖ステラシアター (山梨)',
    note: '結成3周年記念 初の野外ワンマン',
  },

  // ── 高嶺のなでしこ たかねこフェスVol.6〜サマーセッション〜（高貓自辦 multi-artist フェス） ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'たかねこフェスVol.6 〜サマーセッション〜',
    date: '2026-07-12',
    startTime: '12:00',
    venue: 'EX THEATER ROPPONGI (東京)',
    url: 'https://takanenonadeshiko.jp/takanekofes-vol6/',
    note: '高貓主催対バン、α+ / いぎなり東北産 / 22/7 / 可憐なアイボリー など 20 組',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: 'アオゾラサマーフェスティバル2026',
    date: '2026-08-30',
    venue: '豊洲PIT (東京)',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: 'BOKUAO Winter Concert 2026 〜君への贈りもの〜',
    date: '2026-12-14',
    startTime: '18:00',
    venue: 'Kanadevia Hall (東京)',
    url: 'https://bokuao.com/news/detail/5748',
    note: '2026年ラストライブ。開場 17:00、終演後お見送り付き',
  },

  // ── 超ときめき♡宣伝部 きみのハートにロックオンTOUR 2026 (Jul–Oct, 16 公演) ──
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 仙台`,
    date: '2026-07-04',
    startTime: '17:00',
    venue: '仙台サンプラザホール (宮城)',
    url: 'https://toki-sen.com/contents/1061667',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 金沢`,
    date: '2026-07-12',
    startTime: '17:00',
    venue: '本多の森北電ホール (石川)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 栃木`,
    date: '2026-07-26',
    startTime: '17:00',
    venue: '栃木県総合文化センター (栃木)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 八王子`,
    date: '2026-08-02',
    startTime: '17:00',
    venue: 'J:COM ホール八王子 (東京)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 札幌`,
    date: '2026-08-08',
    startTime: '17:00',
    venue: 'カナモトホール (北海道)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 市川`,
    date: '2026-08-11',
    startTime: '17:00',
    venue: '市川市文化会館 (千葉)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 大宮`,
    date: '2026-08-12',
    startTime: '18:00',
    venue: '大宮ソニックシティ 大ホール (埼玉)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 有明 DAY1`,
    date: '2026-08-22',
    startTime: '17:00',
    venue: 'SGC ホール有明 (東京)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 有明 DAY2`,
    date: '2026-08-23',
    startTime: '17:00',
    venue: 'SGC ホール有明 (東京)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 福岡`,
    date: '2026-08-29',
    startTime: '16:00',
    venue: '福岡市民会館 大ホール (福岡)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 名古屋`,
    date: '2026-08-30',
    startTime: '18:00',
    venue: 'Niterra 日本特殊陶業市民会館 (愛知)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 神戸 DAY1`,
    date: '2026-09-12',
    startTime: '17:00',
    venue: 'GLION ARENA KOBE (兵庫)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 神戸 DAY2`,
    date: '2026-09-13',
    startTime: '16:00',
    venue: 'GLION ARENA KOBE (兵庫)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 日本武道館`,
    date: '2026-10-05',
    startTime: '18:00',
    venue: '日本武道館 (東京)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 有明アリーナ DAY1`,
    date: '2026-10-24',
    startTime: '17:00',
    venue: '有明アリーナ (東京)',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 有明アリーナ FINAL`,
    date: '2026-10-25',
    startTime: '16:00',
    venue: '有明アリーナ (東京)',
  },

  // ── 超ときめき♡宣伝部 その他（※2026年8月発表: 2027年春頃をもって活動終了） ──
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'ときめき♡夏のびっちょり祭り2026 ミニライブ＋お見送り会',
    date: '2026-09-05',
    startTime: '15:30',
    venue: '西武園ゆうえんち レッツゴー！レオランド 特設ステージ (埼玉)',
    url: 'https://toki-sen.com/contents/1101621',
    note: '集合 14:30。FC有料 ¥5,000（入園+乗り放題+CD2枚+お見送り券込）',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'ROCK IN JAPAN FESTIVAL 2026',
    date: '2026-09-20',
    startTime: '11:45',
    venue: '千葉市蘇我スポーツ公園 (千葉)',
    url: 'https://toki-sen.com/contents/1083692',
    note: 'とき宣は 9/20 出演（CUTIE STREET は 9/19、ももクロは 9/21）',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念リアルイベント',
    date: '2026-09-22',
    venue: '有明セントラルタワーホールB (東京)',
    url: 'https://toki-sen.com/contents/1083047',
    note: '特典会形式（撮影 / おはなし会など）',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念リアルイベント',
    date: '2026-09-23',
    venue: '有明セントラルタワーホールB (東京)',
    url: 'https://toki-sen.com/contents/1083047',
    note: '特典会形式（撮影 / おはなし会など）',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念リアルイベント',
    date: '2026-10-11',
    venue: 'TODA HALL & CONFERENCE TOKYO ホールA (東京)',
    url: 'https://toki-sen.com/contents/1083047',
    note: '特典会形式',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念リアルイベント',
    date: '2026-10-12',
    venue: 'シティホール＆ギャラリー五反田 (東京)',
    url: 'https://toki-sen.com/contents/1083047',
    note: '特典会形式',
  },
  {
    artistNames: ['超ときめき♡宣伝部', 'ももいろクローバーZ'],
    title: '氣志團万博2026 〜房総爆音リゾート〜 DAY2',
    date: '2026-11-08',
    startTime: '10:30',
    venue: '幕張メッセ国際展示場 4〜7ホール (千葉)',
    url: 'https://www.kishidanbanpaku.com/',
    note: 'フェスは 11/7-8 開催、とき宣・ももクロとも DAY2 出演',
  },

  // ── SWEET STEADY (KAWAII LAB. / ASOBISYSTEM) 2026 夏 ──
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'KAWAII LAB. SESSION 2026 SUMMER DAY1',
    date: '2026-07-10',
    venue: '国立代々木競技場 第一体育館 (東京)',
    note: 'KAWAII LAB. 合同ライブ',
  },
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'KAWAII LAB. SESSION 2026 SUMMER DAY2',
    date: '2026-07-11',
    venue: '国立代々木競技場 第一体育館 (東京)',
    note: 'KAWAII LAB. 合同ライブ',
  },
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'JOIN ALIVE 2026',
    date: '2026-07-19',
    venue: '北海道 (岩見沢)',
    note: '夏フェス出演',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: '栗田なつか 生誕LIVE',
    date: '2026-07-21',
    note: 'SWEET STEADY 栗田なつか 個人生誕祭',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'Osaka Gigantic Music Festival 2026',
    date: '2026-07-26',
    venue: '大阪',
    note: '夏フェス出演',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: '塩川莉世 生誕LIVE',
    date: '2026-07-28',
    note: 'SWEET STEADY 塩川莉世 個人生誕祭',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: SWESTE_RELEASE,
    date: '2026-08-02',
    startTime: '18:00',
    venue: 'セブンパークアリオ柏 屋外スマイルパーク (千葉)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/85497',
    note: 'ミニライブ&特典会',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: SWESTE_RELEASE,
    date: '2026-08-09',
    startTime: '17:00',
    venue: 'ららぽーと豊洲 シーサイドデッキ メインステージ (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/85499',
    note: 'ミニライブ&特典会、CD購入者優先エリアあり・エリア外観覧可',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'TOMAKOMAI MIRAI FEST 2026 DAY2',
    date: '2026-09-13',
    startTime: '11:00',
    venue: 'キラキラ公園 (北海道 苫小牧)',
    url: 'https://miraifest-tomakomai.jp',
    note: '野外フェス出演（DAY1 9/12 は CUTIE STREET）',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'SWEET STEADY ARENA LIVE 2026 -SUMMER- STEADY → REVOLUTION',
    date: '2026-08-23',
    venue: 'ぴあアリーナMM (神奈川)',
    url: 'https://sweetsteady.asobisystem.com/',
    note: '初の単独アリーナ公演',
  },

  // ── SWEET STEADY『SWEET STEP』リリイベ後半戦（9/5-9/7 は関東3連投） ──
  {
    artistNames: ['SWEET STEADY'],
    title: 'バンコク日本博2026',
    date: '2026-08-28',
    venue: 'クイーン・シリキット国立コンベンションセンター (タイ バンコク)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43895',
    note: 'すいすて初の海外公演、入場無料',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_RELEASE} — 所沢`,
    date: '2026-09-05',
    startTime: '14:00',
    venue: 'エミテラス所沢 2F TOKOROZAWA e-CUBE (埼玉)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43897',
    note: 'ミニライブ 14:00 / CD販売 10:10 / 優先エリア集合 13:20。お見送り会＋個別2ショットチェキ。残席あればミニライブのみ観覧フリー',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_RELEASE} — 大特典会`,
    date: '2026-09-06',
    startTime: '10:00',
    venue: 'ベルサール汐留 (東京)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43898',
    note: '6部制 10:00 / 11:20 / 13:20 / 14:40 / 16:40 / 18:00。ミニライブ無し・特典会のみ。HMV 予約シリアル必要',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_RELEASE} — 池袋`,
    date: '2026-09-07',
    startTime: '16:30',
    venue: '池袋・サンシャインシティ 噴水広場 (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/89031',
    note: '9/2 詳細公布。ミニライブ＆特典会。CD販売 12:00、優先エリア集合 16:00',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_RELEASE} — 大特典会`,
    date: '2026-09-22',
    startTime: '10:00',
    venue: '東京流通センター 第二展示場 Fホール (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/88913',
    note: '發售活動，個別2ショットチェキ撮影会のみ。6部制 10:00 / 11:20 / 13:20 / 14:40 / 16:40 / 18:00',
  },

  // ── SWEET STEADY 秋のフェス出演 & 単独公演 ──
  {
    artistNames: ['SWEET STEADY'],
    title: '第43回 マイナビ 東京ガールズコレクション 2026 A/W',
    date: '2026-09-19',
    startTime: '14:00',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43901',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'AGESTOCK2026 in 横浜アリーナ',
    date: '2026-09-20',
    startTime: '18:30',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43902',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'SWEET STEADY 単独公演「お花見会」1部',
    date: '2026-09-21',
    startTime: '14:00',
    venue: 'Zepp Shinjuku (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/88352',
    note: '2公演制、優先スタンディング ¥8,000（FC先行）/ 一般 ¥5,000',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'SWEET STEADY 単独公演「お花見会」2部',
    date: '2026-09-21',
    startTime: '17:30',
    venue: 'Zepp Shinjuku (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/88352',
    note: '2公演制、優先スタンディング ¥8,000（FC先行）/ 一般 ¥5,000',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'MotoGP™ Night Live',
    date: '2026-10-03',
    venue: 'モビリティリゾートもてぎ (栃木)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43904',
    note: 'MotoGP 日本GP 前夜祭',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'マグロック＆ポップ 2026',
    date: '2026-10-04',
    startTime: '11:00',
    venue: '清水マリンパーク (静岡)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/43903',
  },

  // ── SWEET STEADY JAPAN TOUR 2026 -WINTER-（初のホールツアー） ──
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_TOUR} — 厚木`,
    date: '2026-11-13',
    startTime: '18:30',
    venue: '厚木市文化会館 大ホール (神奈川)',
    url: 'https://prtimes.jp/main/html/rd/p/000000821.000017258.html',
    note: '¥7,000',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_TOUR} — 堺`,
    date: '2026-12-03',
    startTime: '18:30',
    venue: 'フェニーチェ堺 大ホール (大阪)',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_TOUR} — 名古屋`,
    date: '2026-12-06',
    startTime: '17:00',
    venue: 'Niterra 日本特殊陶業市民会館 フォレストホール (愛知)',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_TOUR} — 有明`,
    date: '2026-12-18',
    startTime: '18:30',
    venue: 'SGC ホール有明 (東京)',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'SWEET STEADY 3rd ANNIVERSARY LIVE',
    date: '2027-03-04',
    venue: '日本武道館 (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/87830',
    note: '初の武道館、8/23 ぴあアリーナ公演で発表',
  },

  // ── CUTIE STREET (KAWAII LAB. / ASOBISYSTEM) 2026 夏 ──
  // KAWAII LAB. SESSION 7/10-11 と JOIN ALIVE 7/19 は SWEET STEADY の
  // エントリに合同で入れてある（同じイベント）
  {
    artistNames: ['CUTIE STREET'],
    title: 'TOKYO GIRLS MUSIC Fes.',
    date: '2026-07-12',
    venue: 'LINE CUBE SHIBUYA (東京)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET Live in Korea 2026 SUMMER DAY1',
    date: '2026-07-25',
    venue: 'Sejong University (Seoul)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET Live in Korea 2026 SUMMER DAY2',
    date: '2026-07-26',
    venue: 'Sejong University (Seoul)',
  },

  // ── CUTIE STREET 2周年記念（初武道館） & 生誕祭 ──
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET 2nd ANNIVERSARY LIVE 2026「8 TREASURES」DAY1',
    date: '2026-08-25',
    startTime: '18:00',
    venue: '日本武道館 (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/69020',
    note: '初武道館・2周年記念',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET 2nd ANNIVERSARY LIVE 2026「8 TREASURES」DAY2',
    date: '2026-08-26',
    startTime: '17:00',
    venue: '日本武道館 (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/69020',
    note: '初武道館・2周年記念',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: '梅田みゆ生誕祭2026',
    date: '2026-09-14',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    note: 'CUTIE STREET 梅田みゆ 個人生誕祭',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: '2nd ANNIVERSARY「すべての道はKAWAIIにつーず！展」',
    date: '2026-09-05',
    venue: '日本橋三井ホール (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/86474',
    note: '会期 9/5〜9/23、平日 12:00-19:00 / 土日祝 10:00-19:00。当日券 ¥2,800（前売 ¥2,700）',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'TOMAKOMAI MIRAI FEST 2026 DAY1',
    date: '2026-09-12',
    venue: 'キラキラ公園 (北海道 苫小牧)',
    url: 'https://miraifest-tomakomai.jp',
    note: '野外フェス出演（DAY2 9/13 は SWEET STEADY）',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'ROCK IN JAPAN FESTIVAL 2026',
    date: '2026-09-19',
    venue: '千葉市蘇我スポーツ公園 (千葉)',
    note: 'フェス出演（ももクロは 9/21 出演）',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'STARフェス DAY2',
    date: '2026-10-11',
    startTime: '17:00',
    venue: 'ぴあアリーナMM (神奈川)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/86976',
    note: 'フジテレビ主催、INI / THE RAMPAGE など出演',
  },
  {
    artistNames: ['CUTIE STREET', 'SWEET STEADY'],
    title: 'KAWAII LAB. COLLECTION produced by TGC 〜KAWAIIっちゃ in KITAKYUSHU〜',
    date: '2026-10-12',
    startTime: '16:00',
    venue: '北九州メッセ (福岡)',
    note: 'KAWAII LAB. 6組出演',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'MIYAKO ISLAND ROCK FESTIVAL 2026',
    date: '2026-10-17',
    venue: '宮古島コースタルリゾートヒララ (沖縄)',
    note: 'フェス出演',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET Live in Korea 2027 WINTER',
    date: '2027-01-23',
    startTime: '18:00',
    venue: 'KINTEX Hall 9A (韓国 高陽)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/86456',
    note: '初の韓国単独公演、18:00 KST',
  },

  // ── CUTIE STREET JAPAN ARENA TOUR 2026 -AUTUMN- (初アリーナツアー, 7都市13公演) ──
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 横浜`,
    date: '2026-09-23',
    startTime: '17:00',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://cutiestreet.asobisystem.com/',
    note: '指定席 ¥10,000',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 有明 DAY1`,
    date: '2026-09-29',
    venue: '有明アリーナ (東京)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 有明 DAY2`,
    date: '2026-09-30',
    venue: '有明アリーナ (東京)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 宮城 DAY1`,
    date: '2026-10-03',
    venue: 'セキスイハイムスーパーアリーナ (宮城)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 宮城 DAY2`,
    date: '2026-10-04',
    venue: 'セキスイハイムスーパーアリーナ (宮城)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 福岡 DAY1`,
    date: '2026-10-28',
    venue: 'マリンメッセ福岡 A館 (福岡)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 福岡 DAY2`,
    date: '2026-10-29',
    venue: 'マリンメッセ福岡 A館 (福岡)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 神戸 DAY1`,
    date: '2026-10-31',
    venue: '神戸ワールド記念ホール (兵庫)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 神戸 DAY2`,
    date: '2026-11-01',
    venue: '神戸ワールド記念ホール (兵庫)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 広島 DAY1`,
    date: '2026-11-14',
    venue: '広島グリーンアリーナ (広島)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 広島 DAY2`,
    date: '2026-11-15',
    venue: '広島グリーンアリーナ (広島)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 名古屋 DAY1`,
    date: '2026-11-28',
    venue: 'IGアリーナ (愛知)',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: `${CUTIE_ARENA_TOUR} — 名古屋 FINAL`,
    date: '2026-11-29',
    venue: 'IGアリーナ (愛知)',
  },

  // ── KAWAII LAB. 合同イベント 2026 夏〜冬（SWEET STEADY / CUTIE STREET） ──
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'ASOBISYSTEM 19th Anniversary ASOBIEXPO 2026',
    date: '2026-08-18',
    startTime: '17:30',
    venue: 'TOYOTA ARENA TOKYO (東京)',
    url: 'https://asobisystem.com/news/72691/',
    note: 'KAWAII LAB. 全グループ含む全86組出演',
  },
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'KAWAII LAB. Christmas SESSION 2026 DAY1',
    date: '2026-12-12',
    startTime: '17:00',
    venue: '有明アリーナ (東京)',
    url: 'https://kawaiilab.asobisystem.com/news/detail/84218',
    note: 'KAWAII LAB. 合同ライブ',
  },
  {
    artistNames: ['SWEET STEADY', 'CUTIE STREET'],
    title: 'KAWAII LAB. Christmas SESSION 2026 DAY2',
    date: '2026-12-13',
    startTime: '16:00',
    venue: '有明アリーナ (東京)',
    url: 'https://kawaiilab.asobisystem.com/news/detail/84218',
    note: 'KAWAII LAB. 合同ライブ',
  },

  // ── GIFT 〜Girls Idol Festival Tokyo〜（テレ朝主催新フェス、11/27-29） ──
  {
    artistNames: ['超ときめき♡宣伝部', 'CUTIE STREET'],
    title: 'GIFT 〜Girls Idol Festival Tokyo〜 DAY1',
    date: '2026-11-27',
    startTime: '18:00',
    venue: 'SGC ホール有明 (東京)',
    url: 'https://gift-idol.jp/',
    note: '=LOVE / FRUITS ZIPPER / モーニング娘。\'26 なども出演',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'GIFT 〜Girls Idol Festival Tokyo〜 DAY2',
    date: '2026-11-28',
    startTime: '13:00',
    venue: 'SGC ホール有明 + TOYOTA ARENA TOKYO (東京)',
    url: 'https://gift-idol.jp/',
    note: '周遊型 2 会場、振り分け未発表。AKB48 / 日向坂46 なども出演',
  },
  {
    artistNames: ['私立恵比寿中学', 'SWEET STEADY', 'Juice=Juice'],
    title: 'GIFT 〜Girls Idol Festival Tokyo〜 DAY3',
    date: '2026-11-29',
    startTime: '13:00',
    venue: 'SGC ホール有明 + TOYOTA ARENA TOKYO (東京)',
    url: 'https://gift-idol.jp/',
    note: '周遊型 2 会場、振り分け未発表。乃木坂46 / FRUITS ZIPPER なども出演',
  },

  // ── MTV VMAJ 2026（超ときめき♡宣伝部 出演） ──
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'MTV VMAJ 2026',
    date: '2026-10-29',
    startTime: '18:00',
    venue: '東京ドーム (東京)',
    url: 'https://www.mtvjapan.com/event/vmaj/2026/',
    note: 'アワード形式ライブ、=LOVE / ≠ME ほかも出演',
  },

  // ── ももいろクローバーZ 2026 秋〜年末（フェス出演・桃神祭・年末） ──
  // 氣志團万博 11/8 はとき宣のエントリに合同で入れてある（同じイベント）
  {
    artistNames: ['ももいろクローバーZ', '私立恵比寿中学'],
    title: '黒フェス2026〜白黒歌合戦〜',
    date: '2026-09-06',
    startTime: '16:30',
    venue: '豊洲PIT (東京)',
    url: 'http://kurofes.net/',
    note: '松崎しげる主催フェス。開場 15:30、スタンディング ¥9,696',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '中山秀征 HIDE LIVE 2026 ザ･歌謡ショー',
    date: '2026-09-17',
    startTime: '18:00',
    venue: 'EX THEATER ROPPONGI (東京)',
    note: 'ゲスト出演',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'FEST. INAZUMA 2026',
    date: '2026-09-19',
    startTime: '11:30',
    venue: '烏丸半島芝生広場 (滋賀)',
    url: 'https://fest-inazuma.com/',
    note: '旧イナズマロックフェス。開場 10:00 / 終演 19:00、出演枠時刻未発表',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'ROCK IN JAPAN FESTIVAL 2026',
    date: '2026-09-21',
    startTime: '14:00',
    venue: '千葉市蘇我スポーツ公園 (千葉)',
    note: 'LOTUS STAGE 出演',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'ももクロ秋の桃神祭2026 in千葉県長生村 DAY1「鬼になった桃神様」',
    date: '2026-10-17',
    startTime: '15:00',
    venue: '尼ヶ台総合公園 (千葉)',
    url: 'https://www.momoclo.net/tohjinsai2026/',
    note: '開催地公募型野外ライブ（春の一大事の代替）',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'ももクロ秋の桃神祭2026 in千葉県長生村 DAY2「祀れ、われらの偶像」',
    date: '2026-10-18',
    startTime: '15:00',
    venue: '尼ヶ台総合公園 (千葉)',
    url: 'https://www.momoclo.net/tohjinsai2026/',
    note: '開催地公募型野外ライブ（春の一大事の代替）',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '第10回 ももいろ歌合戦',
    date: '2026-12-31',
    venue: '有明アリーナ (東京)',
    note: '有明アリーナ初開催、開演時刻・出演者未発表',
  },

  // ── ももクリDelivery（クリスマスホールツアー、全11公演。SSA改修のためツアー形式） ──
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 有明`,
    date: '2026-10-30',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 福山`,
    date: '2026-11-02',
    startTime: '19:00',
    venue: 'ふくやま芸術文化ホール リーデンローズ (広島)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 神戸`,
    date: '2026-11-06',
    startTime: '19:00',
    venue: '神戸国際会館 こくさいホール (兵庫)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 京都`,
    date: '2026-11-07',
    startTime: '17:30',
    venue: 'ロームシアター京都 (京都)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 新潟`,
    date: '2026-11-22',
    startTime: '16:00',
    venue: '新潟テルサ (新潟)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 一宮`,
    date: '2026-11-23',
    startTime: '17:30',
    venue: '一宮市民会館 (愛知)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 福岡`,
    date: '2026-11-27',
    startTime: '19:00',
    venue: '福岡市民ホール 大ホール (福岡)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 札幌 番外編`,
    date: '2026-12-03',
    startTime: '19:00',
    venue: 'Zepp Sapporo (北海道)',
    url: MOMOCLO_XMAS_URL,
    note: 'NORTHERN LIGHTS CHRISTMAS GIG、この日限りのライブハウス公演',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 有明 FINAL DAY1`,
    date: '2026-12-11',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 有明 FINAL DAY2`,
    date: '2026-12-12',
    startTime: '17:00',
    venue: 'SGC ホール有明 (東京)',
    url: MOMOCLO_XMAS_URL,
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: `${MOMOCLO_XMAS} — 有明 FINAL DAY3`,
    date: '2026-12-13',
    startTime: '16:00',
    venue: 'SGC ホール有明 (東京)',
    url: MOMOCLO_XMAS_URL,
  },

  // ── Juice=Juice (Hello! Project) 2026 夏〜秋 ──
  // ハロ！コン 2026 は 8/9 TOYOTA ARENA TOKYO で終了済みのため未収録
  {
    artistNames: ['Juice=Juice'],
    title: 'ナルチカ 2026 Juice=Juice in 高石 1回目',
    date: '2026-08-23',
    startTime: '13:30',
    venue: 'アプラたかいし 大ホール (大阪)',
    url: 'https://helloproject.com/event/65c7bca38a9204efa47e4e0ba5bace61297d7299/',
    note: '大阪府高石市×Juice=Juice 地域活性化コンサート、昼夜2公演',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'ナルチカ 2026 Juice=Juice in 高石 2回目',
    date: '2026-08-23',
    startTime: '16:30',
    venue: 'アプラたかいし 大ホール (大阪)',
    url: 'https://helloproject.com/event/65c7bca38a9204efa47e4e0ba5bace61297d7299/',
    note: '大阪府高石市×Juice=Juice 地域活性化コンサート、昼夜2公演',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'Kohmi EXPO 2026',
    date: '2026-09-03',
    startTime: '18:30',
    venue: 'LINE CUBE SHIBUYA (東京)',
    note: '広瀬香美プロデュースフェス出演',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'CDTVライブ！ライブ！秋の大感謝祭2026',
    date: '2026-09-11',
    startTime: '18:00',
    venue: '東京ガーデンシアター (東京)',
    note: 'TBS 有観客ライブ、NiziU / FRUITS ZIPPER と共演',
  },
  {
    artistNames: ['Juice=Juice', '高嶺のなでしこ'],
    title: '第4回 IDOL RUNWAY COLLECTION 2026 A/W',
    date: '2026-09-20',
    startTime: '12:00',
    venue: '横浜アリーナ (神奈川)',
    note: 'J=J はハロプロ初出演。開場 11:00 / 終演予定 16:00。CANDY TUNE / 日向坂46 / FRUITS ZIPPER / ≒JOY ほか',
  },

  // ── Juice=Juice Room Tour 2026 「5ROOMS」 (9/18–11/25, 武道館含む) ──
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 厚木 初日`,
    date: '2026-09-18',
    startTime: '19:00',
    venue: '厚木市文化会館 大ホール (神奈川)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 厚木 昼公演`,
    date: '2026-09-19',
    startTime: '13:45',
    venue: '厚木市文化会館 大ホール (神奈川)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 厚木 夜公演`,
    date: '2026-09-19',
    startTime: '17:15',
    venue: '厚木市文化会館 大ホール (神奈川)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 広島 昼公演`,
    date: '2026-09-22',
    startTime: '15:30',
    venue: 'JMSアステールプラザ 大ホール (広島)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 広島 夜公演`,
    date: '2026-09-22',
    startTime: '19:00',
    venue: 'JMSアステールプラザ 大ホール (広島)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 京都`,
    date: '2026-09-24',
    startTime: '19:00',
    venue: 'ロームシアター京都 メインホール (京都)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 福岡 昼公演`,
    date: '2026-09-26',
    startTime: '15:30',
    venue: 'SAWARAPIA 大ホール (福岡)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 福岡 夜公演`,
    date: '2026-09-26',
    startTime: '19:00',
    venue: 'SAWARAPIA 大ホール (福岡)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 福岡 昼公演`,
    date: '2026-09-27',
    startTime: '13:15',
    venue: 'SAWARAPIA 大ホール (福岡)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 福岡 夜公演`,
    date: '2026-09-27',
    startTime: '16:45',
    venue: 'SAWARAPIA 大ホール (福岡)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 名古屋 昼公演`,
    date: '2026-10-03',
    startTime: '15:15',
    venue: 'Niterra日本特殊陶業市民会館 ビレッジホール (愛知)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 名古屋 夜公演`,
    date: '2026-10-03',
    startTime: '18:45',
    venue: 'Niterra日本特殊陶業市民会館 ビレッジホール (愛知)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 大阪 昼公演`,
    date: '2026-10-10',
    startTime: '14:30',
    venue: 'NHK大阪ホール (大阪)',
    url: JJ_5ROOMS_URL,
    note: '10月10日は Juice=Juice の日',
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 大阪 夜公演`,
    date: '2026-10-10',
    startTime: '18:00',
    venue: 'NHK大阪ホール (大阪)',
    url: JJ_5ROOMS_URL,
    note: '10月10日は Juice=Juice の日',
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 仙台 昼公演`,
    date: '2026-10-18',
    startTime: '15:30',
    venue: '東京エレクトロンホール宮城 (宮城)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 仙台 夜公演`,
    date: '2026-10-18',
    startTime: '19:00',
    venue: '東京エレクトロンホール宮城 (宮城)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 桐生 昼公演`,
    date: '2026-10-25',
    startTime: '15:15',
    venue: '美喜仁桐生文化会館 シルクホール (群馬)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 桐生 夜公演`,
    date: '2026-10-25',
    startTime: '18:45',
    venue: '美喜仁桐生文化会館 シルクホール (群馬)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} -SUITE-` + ' — 日本武道館 特別公演',
    date: '2026-11-06',
    startTime: '18:00',
    venue: '日本武道館 (東京)',
    url: JJ_5ROOMS_URL,
    note: '追加公演（8/12 発表）',
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 大阪・オリックス劇場`,
    date: '2026-11-13',
    startTime: '19:00',
    venue: 'オリックス劇場 (大阪)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 東京 昼公演`,
    date: '2026-11-16',
    startTime: '15:15',
    venue: 'Kanadevia Hall (東京)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 東京 夜公演`,
    date: '2026-11-16',
    startTime: '19:00',
    venue: 'Kanadevia Hall (東京)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 東京 昼公演`,
    date: '2026-11-17',
    startTime: '15:00',
    venue: 'Kanadevia Hall (東京)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} — 東京 夜公演`,
    date: '2026-11-17',
    startTime: '18:45',
    venue: 'Kanadevia Hall (東京)',
    url: JJ_5ROOMS_URL,
  },
  {
    artistNames: ['Juice=Juice'],
    title: `${JJ_5ROOMS} -ROYAL SUITE-` + ' — 横浜 FINAL',
    date: '2026-11-25',
    startTime: '18:00',
    venue: 'ぴあアリーナMM (神奈川)',
    url: JJ_5ROOMS_URL,
    note: 'ツアーファイナル（追加公演）',
  },

  // ── Juice=Juice FC スペシャルライブ（10/10 は Juice=Juice の日） ──
  {
    artistNames: ['Juice=Juice'],
    title: 'Juice=Juiceスペシャルライブ2026 〜10月10日はJuice=Juiceの日〜 DAY1',
    date: '2026-10-20',
    venue: 'かつしかシンフォニーヒルズ モーツァルトホール (東京)',
    note: '生バンド編成 / FC会員限定 / 開演時間未発表',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'Juice=Juiceスペシャルライブ2026 〜10月10日はJuice=Juiceの日〜 DAY2',
    date: '2026-10-21',
    venue: 'かつしかシンフォニーヒルズ モーツァルトホール (東京)',
    note: '生バンド編成 / FC会員限定 / 開演時間未発表',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'ポムフェス POMPOMPURIN FESTIVAL',
    date: '2026-09-12',
    startTime: '11:20',
    venue: '横浜赤レンガ倉庫 イベント広場 (神奈川)',
    note: 'サンリオ主催、入替制。前方エリア券 ¥1,500',
  },
  {
    artistNames: ['Juice=Juice'],
    title: '工藤由愛 バースデーイベント2026',
    date: '2026-09-28',
    venue: 'せたがやイーグレットホール (東京)',
    note: 'FC イベント',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'Juice=Juice FCイベント2026 〜メリクリ×Juice×Box〜',
    date: '2026-12-09',
    venue: '市川市文化会館 大ホール (千葉)',
    note: 'FC 会員限定',
  },
  // ── 2026-09-01 追加分: KAWAII LAB. / とき宣 ──
  {
    artistNames: ['SWEET STEADY'],
    title: '北海道日本ハムファイターズ vs ソフトバンク戦 スペシャルライブ',
    date: '2026-09-02',
    startTime: '17:40',
    venue: 'エスコンフィールドHOKKAIDO (北海道)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/44454',
    note: '庄司なぎさ始球式、キツネダンス、試合後スペシャルライブ',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: `${SWESTE_RELEASE} — 札幌`,
    date: '2026-09-14',
    venue: 'サッポロファクトリー アトリウム (北海道)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/44456',
    note: '9/13 苫小牧の翌日、時間未発表',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念 オンライン個別お話し会',
    date: '2026-10-01',
    startTime: '19:00',
    venue: 'オンライン',
    url: 'https://toki-sen.com/contents/1092222',
    note: '1部 19:00 / 2部 20:50',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'GFEST.2026',
    date: '2026-10-10',
    venue: 'Gメッセ群馬 (群馬)',
    url: 'https://toki-sen.com/contents/1101209',
    note: 'スタンディング ¥11,000 / 指定席 ¥13,500',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'HAPPINESS JAM 2026',
    date: '2026-10-17',
    startTime: '14:00',
    venue: 'HAPPINESS ARENA 長崎スタジアムシティ (長崎)',
    url: 'https://www.nagasakistadiumcity.com/news/20260821/',
    note: '新しい学校のリーダーズ / 水曜日のカンパネラ と共演',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'FM AICHI 公開録音 SWEET STEADY SPECIAL LIVE',
    date: '2026-10-18',
    startTime: '13:00',
    venue: 'ナガシマスパードーム (三重)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/88756',
    note: '観覧無料（別途入園料）、終了後に特典会あり',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'SWEET STEADY 庄司なぎさ BIRTHDAY LIVE 2026',
    date: '2026-10-26',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: 'https://sweetsteady.asobisystem.com/news/detail/88494',
    note: '全席指定 ¥6,500、開場 17:30',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '「大盛りハッピー」発売記念 FC限定リアルサイン会',
    date: '2026-11-01',
    venue: '都内（当選者のみ会場通知）(東京)',
    url: 'https://toki-sen.com/contents/1092181',
    note: '抽選制',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: "LARME FES '26",
    date: '2026-11-07',
    startTime: '16:00',
    venue: '東京ガーデンシアター (東京)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/44462',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET 古澤里紗 生誕祭 2026',
    date: '2026-11-09',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/88510',
    note: '全席指定 ¥6,500、開場 17:30',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET 板倉可奈 生誕祭 2026',
    date: '2026-11-11',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/88514',
    note: '全席指定 ¥6,500、開場 17:30',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: 'FM大阪 超♡わかりみ〜てぃんぐ!! Vol.3',
    date: '2026-11-13',
    startTime: '19:00',
    venue: 'Zepp Osaka Bayside (大阪)',
    url: 'https://toki-sen.com/contents/1101208',
    note: 'ライブ＋公開収録、¥7,150＋ドリンク代',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: `${TOKISEN_TOUR} — 大分 追加公演`,
    date: '2026-11-14',
    startTime: '17:00',
    venue: 'iichiko グランシアタ (大分)',
    url: 'https://toki-sen.com/contents/1105146',
    note: '8/30 発表の追加公演、¥8,800',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'TGC TOYAMA 2026 by TOKYO GIRLS COLLECTION',
    date: '2026-11-21',
    startTime: '14:00',
    venue: 'YKK AP ARENA (富山)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/44463',
  },
  {
    artistNames: ['SWEET STEADY'],
    title: 'WONDERLIVET 2026',
    date: '2026-11-22',
    venue: 'KINTEX HALL 7-10 (韓国 高陽)',
    url: 'https://sweetsteady.asobisystem.com/live_information/detail/44465',
    note: '初の韓国出演、フェス会期 11/20-22 の最終日',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'CUTIE STREET 佐野愛花 生誕祭 2026',
    date: '2026-11-26',
    startTime: '19:00',
    venue: 'SGC ホール有明 (東京)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/88521',
    note: '全席指定 ¥6,500、開場 17:30',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'HIROSHIMA CONTI-NeW FeS 2026 DAY1',
    date: '2026-12-05',
    venue: '広島グリーンアリーナ (広島)',
    url: 'https://cutiestreet.asobisystem.com/live_information/detail/42404',
    note: '初出演',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'HIROSHIMA CONTI-NeW FeS 2026 DAY2',
    date: '2026-12-06',
    venue: '広島グリーンアリーナ (広島)',
    url: 'https://cutiestreet.asobisystem.com/live_information/detail/42405',
    note: '初出演',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '超ときめき♡宣伝部のどきどきクリスマスパーティー2026 DAY1',
    date: '2026-12-12',
    venue: '京王アリーナ TOKYO (東京)',
    url: 'https://toki-sen.com/contents/1105887',
    note: 'ときクリ2026（8/30 発表）。時間・チケット後日発表',
  },
  {
    artistNames: ['超ときめき♡宣伝部'],
    title: '超ときめき♡宣伝部のどきどきクリスマスパーティー2026 DAY2',
    date: '2026-12-13',
    venue: '京王アリーナ TOKYO (東京)',
    url: 'https://toki-sen.com/contents/1105887',
    note: 'ときクリ2026（8/30 発表）。時間・チケット後日発表',
  },
  {
    artistNames: ['CUTIE STREET'],
    title: 'ASOBIEXPO HAWAII 2027 – Japanese Pop Culture Experience –',
    date: '2027-03-08',
    venue: 'Tom Moffatt Waikiki Shell (米国 ホノルル)',
    url: 'https://cutiestreet.asobisystem.com/news/detail/88537',
    note: 'きゃりーぱみゅぱみゅ / FRUITS ZIPPER / 新しい学校のリーダーズ / CANDY TUNE と共演',
  },
  // ── 2026-09-01 追加分: 高嶺 / 僕青 / エビ中 ──
  {
    artistNames: ['高嶺のなでしこ'],
    title: '高嶺のなでしこ ワンマンライブ 〜CROWNED IN BLOOM〜',
    date: '2026-09-13',
    startTime: '14:30',
    venue: 'Shibuya LOVEZ (東京)',
    url: 'https://takanenonadeshiko.jp/onemanlive-crownedinbloom/',
    note: '開場 13:30。終演後に個別2ショット撮影会 4部制 17:00 / 18:00 / 19:00 / 20:00。チケット 9/2 0:00〜 e+',
  },
  {
    artistNames: ['高嶺のなでしこ'],
    title: 'NATSLIVE「たかねこ初恋キッチン。」',
    date: '2026-09-28',
    venue: '配信 (NATSLIVE)',
    note: '出演メンバー後日発表',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が観たかったファンミ vol.2 1部',
    date: '2026-09-12',
    startTime: '15:30',
    venue: 'SHIBUYA PLEASURE PLEASURE (東京)',
    url: 'https://bokuao.com/news/detail/5747',
    note: 'FC限定、来場者全員お見送り付き。開場 14:45',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: '僕が観たかったファンミ vol.2 2部',
    date: '2026-09-12',
    startTime: '19:00',
    venue: 'SHIBUYA PLEASURE PLEASURE (東京)',
    url: 'https://bokuao.com/news/detail/5747',
    note: 'FC限定、来場者全員お見送り付き。開場 18:15',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-09-05',
    venue: '有明セントラルタワーホール＆カンファレンス ホールA (東京)',
    url: 'https://bokuao.com/news/detail/5773',
    note: '当日予約販売のみ、8thシングルMV衣装。時間未発表',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-09-19',
    startTime: '12:00',
    venue: 'オンライン (WithLIVE)',
    url: 'https://bokuao.com/news/detail/5777',
    note: '7部制 12:00 / 13:15 / 14:30 / 16:00 / 17:15 / 18:30 / 19:45、約25秒',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-09-20',
    startTime: '12:00',
    venue: 'オンライン (WithLIVE)',
    url: 'https://bokuao.com/news/detail/5777',
    note: '7部制 12:00〜20:45',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-09-23',
    venue: '大手町プレイスホール＆カンファレンス ホールA＆B (東京)',
    url: 'https://bokuao.com/news/detail/5773',
    note: '当日予約販売のみ、全国ツアー2026春衣装',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-09-27',
    venue: '新宿住友ホール (東京)',
    url: 'https://bokuao.com/news/detail/5773',
    note: '当日予約販売のみ、9thシングル制服',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-10-04',
    venue: 'オンライン',
    url: 'https://bokuao.com/news/detail/5773',
    note: '詳細後日',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-10-10',
    venue: 'オンライン',
    url: 'https://bokuao.com/news/detail/5773',
    note: '詳細後日',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-10-12',
    venue: '有明セントラルタワーホール＆カンファレンス ホールB (東京)',
    url: 'https://bokuao.com/news/detail/5773',
    note: '抽選 9/18 18:00〜',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-10-18',
    venue: '松下IMPホール (大阪)',
    url: 'https://bokuao.com/news/detail/5773',
    note: '抽選 9/18 18:00〜',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-10-24',
    venue: 'オンライン',
    url: 'https://bokuao.com/news/detail/5773',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-10-25',
    venue: 'COMTEC PORTBASE (愛知)',
    url: 'https://bokuao.com/news/detail/5773',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-11-03',
    venue: '新宿住友ホール (東京)',
    url: 'https://bokuao.com/news/detail/5773',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} 個別握手会`,
    date: '2026-11-07',
    venue: '有明セントラルタワーホール＆カンファレンス ホールB (東京)',
    url: 'https://bokuao.com/news/detail/5773',
  },
  {
    artistNames: ['僕が見たかった青空'],
    title: `${BOKUAO_9TH} オンライン個別お話し会`,
    date: '2026-11-08',
    venue: 'オンライン',
    url: 'https://bokuao.com/news/detail/5773',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'NATSLIVE「私立恵比寿中学SPクッキング」',
    date: '2026-09-19',
    startTime: '21:00',
    venue: '配信 (NATSLIVE)',
    note: '真山りか・中山莉子 出演',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '『新春大学芸会2026』発売記念 オンライン個別1分サイン会 追加開催',
    date: '2026-09-28',
    startTime: '18:30',
    venue: 'オンライン (forTUNE meets)',
    url: 'https://www.shiritsuebichu.jp/media/95713/',
    note: '1部 18:30 / 2部 20:30、全8名参加',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '真山りか 生誕ソロライブ',
    date: '2026-12-16',
    venue: 'Zepp DiverCity (TOKYO)',
    url: 'https://www.shiritsuebichu.jp/media/15620/',
    note: 'エビ中 真山りか 個人生誕祭。時間未発表',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: 'エビ中 クリスマスイベント（正式タイトル未発表）',
    date: '2026-12-26',
    venue: 'EX THEATER ROPPONGI (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95127/',
    note: '年末公演枠、詳細後日',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '大学芸会2027 This is GR8 DAY1',
    date: '2027-02-06',
    startTime: '18:00',
    venue: '東京ガーデンシアター (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95128/',
    note: '開場 17:00。従来の「新春大学芸会」から改題',
  },
  {
    artistNames: ['私立恵比寿中学'],
    title: '大学芸会2027 This is GR8 DAY2',
    date: '2027-02-07',
    startTime: '16:00',
    venue: '東京ガーデンシアター (東京)',
    url: 'https://www.shiritsuebichu.jp/media/95129/',
    note: '開場 15:00',
  },
  // ── 2026-09-06 追加分: Juice=Juice ──
  {
    artistNames: ['Juice=Juice'],
    title: 'Livejack 2026 SMASH BEAT SP',
    date: '2026-10-31',
    startTime: '15:30',
    venue: '大阪城ホール (大阪)',
    url: 'https://helloproject.com/juicejuice/event/77c8f531d495ecbf427776654a9aa65e08e4a47520497a66a761b79bd3dd817a/',
    note: '9/6 核對追加。開場 14:30。BEYOOOOONDS ほかと共演',
  },
  // ── 2026-09-01 追加分: J=J / ももクロ ──
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'AYAKA VACATION マレーシアの旅（佐々木彩夏 FC旅行企画）',
    date: '2026-09-10',
    venue: 'クアラルンプール (マレーシア)',
    url: 'https://www.momoclo.net/archives/news/260611_06',
    note: '9/10 成田発〜9/13 成田着。この期間あーりんは国内出演なし',
  },
  {
    artistNames: ['Juice=Juice'],
    title: 'MotoGP™ Night Live',
    date: '2026-10-02',
    venue: 'モビリティリゾートもてぎ (栃木)',
    note: 'MotoGP 日本GP 関連。翌 10/3 は SWEET STEADY が同会場に出演',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '佐々木彩夏 1st写真集「ぺろり」お渡しイベント @大阪',
    date: '2026-10-11',
    startTime: '12:00',
    venue: 'TSUTAYA EBISUBASHI (大阪)',
    url: 'https://www.momoclo.net/archives/news/260819_01',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '佐々木彩夏 1st写真集「ぺろり」ハードロックカフェ横浜 プレミアムイベント',
    date: '2026-10-12',
    startTime: '10:30',
    venue: 'ハードロックカフェ横浜 (神奈川)',
    url: 'https://www.stardustpictures.co.jp/book/2026/sasakiayaka1st_event_1.html',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '佐々木彩夏 1st写真集「ぺろり」お渡しイベント @東京',
    date: '2026-10-12',
    startTime: '14:00',
    venue: 'SHIBUYA TSUTAYA (東京)',
    url: 'https://www.momoclo.net/archives/news/260819_01',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'SPOOKY PUMPKIN 2026',
    date: '2026-10-31',
    startTime: '22:00',
    venue: 'サンリオピューロランド (東京)',
    url: 'https://www.puroland.jp/event-campaign/spookypumpkin2026/',
    note: '佐々木彩夏 出演、オールナイトイベント。開場 21:30',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '15th Anniversary テレビ朝日ドリームフェスティバル2026',
    date: '2026-11-21',
    startTime: '15:00',
    venue: 'Kアリーナ横浜 (神奈川)',
    url: 'https://dreamfestival.jp/',
    note: 'ももクロは 11/21 のみ出演。Aぇ! group / Novelbright ほか。開場 13:30',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '玉井詩織 Billboard Live Tour 2027〜With the music〜 @東京',
    date: '2027-01-21',
    startTime: '18:00',
    venue: 'ビルボードライブ東京 (東京)',
    url: 'https://www.momoclo.net/archives/news/260821_01',
    note: '1日2公演 18:00 / 21:00',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '玉井詩織 Billboard Live Tour 2027〜With the music〜 @東京',
    date: '2027-01-22',
    startTime: '18:00',
    venue: 'ビルボードライブ東京 (東京)',
    url: 'https://www.momoclo.net/archives/news/260821_01',
    note: '1日2公演 18:00 / 21:00',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '玉井詩織 Billboard Live Tour 2027〜With the music〜 @大阪',
    date: '2027-01-25',
    startTime: '18:00',
    venue: 'ビルボードライブ大阪 (大阪)',
    url: 'https://www.momoclo.net/archives/news/260821_01',
    note: '1日2公演 18:00 / 21:00',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: '佐々木彩夏 ソロコンサート',
    date: '2027-01-30',
    venue: '東京体育館 (東京)',
    note: '時刻未発表',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'ももクロくらぶxoxo 〜バレンタイン DE NIGHT だぁ〜Z！2027 DAY1',
    date: '2027-02-13',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://event.1242.com/events/momoclo_valentine/',
    note: 'ニッポン放送主催、時刻未発表',
  },
  {
    artistNames: ['ももいろクローバーZ'],
    title: 'ももクロくらぶxoxo 〜バレンタイン DE NIGHT だぁ〜Z！2027 DAY2',
    date: '2027-02-14',
    venue: '横浜アリーナ (神奈川)',
    url: 'https://event.1242.com/events/momoclo_valentine/',
    note: 'ニッポン放送主催、時刻未発表',
  },
]

export async function loadSeedData(): Promise<{
  artistsAdded: number
  eventsAdded: number
}> {
  const nameToId: Record<string, string> = {}

  for (const spec of ARTISTS) {
    const artist = await createArtist(spec)
    nameToId[spec.name] = artist.id
  }

  let eventsAdded = 0
  for (const spec of EVENTS) {
    const artistIds = spec.artistNames
      .map((n) => nameToId[n])
      .filter((id): id is string => Boolean(id))
    if (artistIds.length === 0) continue
    await createEvent({
      artistIds,
      title: spec.title,
      date: spec.date,
      startTime: spec.startTime,
      venue: spec.venue,
      url: spec.url,
      note: spec.note,
    })
    eventsAdded += 1
  }

  return { artistsAdded: ARTISTS.length, eventsAdded }
}
